import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar/Navbar';
import NextThemeProvider from '@/components/Providers/NextThemeProvider';
import Footer from '@/components/Footer';
import NextAuthSessionProvider from '@/providers/NextAuthSessionProvider';

// font family
const inter = Inter({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

// metadata
export const metadata = {
  title: 'Car Doctor',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg', // standard favicon
    shortcut: '/logo.svg', // old browsers
    apple: '/logo.svg', // iOS devices
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased `}>
        <NextAuthSessionProvider>
          <NextThemeProvider>
            {/* navbar made by DaisyUi */}
            <nav className="sticky top-0 w-full z-[9999]">
              <Navbar />
            </nav>

            {/* main section */}
            <main>{children}</main>

            {/* footer */}
            <footer>
              <Footer />
            </footer>
          </NextThemeProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
